%devalloc() - Allocates an ALP hardware system (board set)

% INPUT: dll_name = name of the dll file (without file extensions)  
% OUTPUT: hdevice = device handle generated by allocate function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function[hdevice] = devalloc(dll_name)
deviceid = uint32(0);
hdevice = uint32(1); %ALP device identifier for which the information is requested
DeviceIdPtr = libpointer('uint32Ptr', hdevice); %make an outpointer to write
[return_DevAlloc, hdevice] = calllib(dll_name, 'AlpDevAlloc', deviceid, hdevice, DeviceIdPtr);
errval = errorcheck(return_DevAlloc);
if errval == 1
    unloadlibrary alpV42
end
end
    
 
    
    
    
    